# VARIÁVEIS
@baseUrl = http://localhost:3333

# HEALTH CHECK
# @name healthCheck
GET {{baseUrl}}/health

###

# GET ROOMS
# @name getRooms
GET {{baseUrl}}/rooms

###

# CREATE ROOM
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Ricardo",
  "description": "Desenvolvedor Front-End"
}

###

@roomId = {{ createRoom.response.body.$.roomId }}

###

# GET ROOM QUESTIONS
# @name getRoomsQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# CREATE QUESTION
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
  "question": "Qual o nome do personagem principal do filme Avatar?",
}